// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJqlijlXzXSr73239ePZbtHFS2-05WjbI',
    appId: '1:271776516578:web:c368460431ac4d03a851bb',
    messagingSenderId: '271776516578',
    projectId: 'srivishshopping',
    authDomain: 'srivishshopping.firebaseapp.com',
    storageBucket: 'srivishshopping.firebasestorage.app',
    measurementId: 'G-87E5XL077B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyNqG9teYHhyf3mGSVxsNe2d35z3Wj0XM',
    appId: '1:271776516578:android:3d5a83c3e20146d0a851bb',
    messagingSenderId: '271776516578',
    projectId: 'srivishshopping',
    storageBucket: 'srivishshopping.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSe0E36esdf5gWRhoEbahVqPkeLzYxebc',
    appId: '1:271776516578:ios:e1fd1a252b930619a851bb',
    messagingSenderId: '271776516578',
    projectId: 'srivishshopping',
    storageBucket: 'srivishshopping.firebasestorage.app',
    iosBundleId: 'com.example.mkartApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSe0E36esdf5gWRhoEbahVqPkeLzYxebc',
    appId: '1:271776516578:ios:e1fd1a252b930619a851bb',
    messagingSenderId: '271776516578',
    projectId: 'srivishshopping',
    storageBucket: 'srivishshopping.firebasestorage.app',
    iosBundleId: 'com.example.mkartApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJqlijlXzXSr73239ePZbtHFS2-05WjbI',
    appId: '1:271776516578:web:ce8d600a2323f32aa851bb',
    messagingSenderId: '271776516578',
    projectId: 'srivishshopping',
    authDomain: 'srivishshopping.firebaseapp.com',
    storageBucket: 'srivishshopping.firebasestorage.app',
    measurementId: 'G-PZEKX7MXN1',
  );
}
